### ISSUE TITLE
ImportError when run actionlib_test.py

### ISSUE THREAD

**Issue by LongfeiProjects** [tork-a/executive_smach_tutorials-release#1]
Hi, 
I am learning smach and found this tutorial. However, I found the following error while I run both actionlib examples (actionlib_test.py and actionlib2_test.py) under folder executive_smach_tutorials/examples. The error messages are below: 

Traceback (most recent call last):
  File "./actionlib_test.py", line 25, in <module>
    from smach_tutorials.msg import TestAction, TestGoal
ImportError: No module named smach_tutorials.msg

I didn't find "smach_tutorials.msg" manually neither. Therefore, this error is quite reasonable for me unless I missed a msg package with the same name.  I didn't found any similar files in other forked copies as well, and most of them are not maintained for long time. Does this error appear on your side as well? Any suggestion for the solution? 

Many thanks!

**Comment by LongfeiProjects** [comment]
Hi,
I just found the solution and it appears quite simple.  It was one step further click before I open this issue:
change the line "smach_tutorials.msg" into "actionlib.msg" will solve the problem.

Since this is solved, I would just close it.

**Comment by k-okada** [comment]
may be you forget to run 'catkin_make' and/or 'source devel/setup.bash '
update your ROS_PACKAGE_PATH

--
◉ Kei Okada


2018-05-16 1:06 GMT+09:00 Longfei_Zhao <notifications@github.com>:
